name: euler
description: A series of challenging mathematical/computer programming problems.
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
